import Head from 'next/head'
import dynamic from 'next/dynamic'

const Header = dynamic<{teste:string}>(()=> import('header/nav'))
const HeaderPage = dynamic(()=> import('header/pages'))

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
      <HeaderPage />
      <h1>testando</h1>
      <Header teste='teste de prop coisa linda testadndo'/>
      </main>
    </>
  )
}
